workflows:
  workflows/release.yml:
    jobs:
      build_docs:
        strategy:
          matrix:
            xcode: latest

  workflows/tests.yml:
    jobs:
      macos_tests:
        strategy:
          matrix:
            xcode:
              - last-major
              - latest
              - latest-beta
      ios_tvos_watchos_maccatalyst_tests:
        strategy:
          matrix:
            xcode:
              - "11.7"
              - last-major
              - latest
              - latest-beta
